export const GET_ROLES_SUCCESS="GET_ROLES_SUCCESS"
export const GET_REQUEST_SUCCESS="GET_REQUEST_SUCCESS"
export const GET_PAGES_SUCCESS="GET_REQUEST_SUCCESS"
export const GET_LOGIN_SUCCESS="GET_TOKEN_SUCCESS"
export const GET_ROLES_PAGES_SUCCESS="GET_ROLES_PAGES_SUCCESS"
export const GET_PAGES_REQUEST_SUCCESS="GET_PAGES_REQUEST_SUCCESS"

export const CREATE_ROLES_SUCCESS="GET_ROLES_SUCCESS"
export const CREATE_REQUEST_SUCCESS="GET_REQUEST_SUCCESS"
export const CREATE_PAGES_SUCCESS="GET_REQUEST_SUCCESS"
export const CREATE_ROLES_PAGES_SUCCESS="CREATE_ROLES_PAGES_SUCCESS"
export const CREATE_PAGES_REQUEST_SUCCESS="CREATE_PAGES_REQUEST_SUCCESS"

export const UPDATE_ROLES_SUCCESS="GET_ROLES_SUCCESS"
export const UPDATE_REQUEST_SUCCESS="GET_REQUEST_SUCCESS"
export const UPDATE_PAGES_SUCCESS="GET_REQUEST_SUCCESS"
export const UPDATE_ROLES_PAGES_SUCCESS="CREATE_ROLES_PAGES_SUCCESS"
export const UPDATE_PAGES_REQUEST_SUCCESS="UPDATE_PAGES_REQUEST_SUCCESS"



export const CHANGE_ROLES="CHANGE_ROLES"
export const CHANGE_REQUEST="CHANGE_REQUEST"
export const CHANGE_PAGES="CHANGE_PAGES"